### ISSUE TITLE
Saving a Script Event in Script Canvas tool shows an error when cancelled

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#11168]
**Describe the bug**
This issue affects specifically the preview Script Event feature in Script Canvas, **not** the Asset Editor. When saving the Script Event, if the user selects "Cancel" or quits the Save As... window, a pop-up with an "Invalid file name" error is displayed.
This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Open Script Canvas.
2. Select Script Events [PREVIEW]>Add Script Event Helpers.
3. Open Tools>Variable Manager.
4. In the Variable Manager, change the Default Values of 4 created strings so that they start with a letter (e.g., "test").
5. Select Script Events [PREVIEW]>Save As Script Event and click "Cancel" or close the Save As... window.

**Expected behavior**
The window closes, no errors appear.

**Actual behavior**
An error window pops up.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/183628852-076d9e05-941f-424e-ab8f-0c388970f29c.mp4

**Found in Branch**
Development (5889b75)

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by AMZN-daimini** [comment]
This may be a duplicate, or related to this: https://github.com/o3de/o3de/pull/11084

**Comment by lsemp3d** [comment]
I fixed this before I saw there was an issue for it :)

**Comment by LB-KatarzynaDylska** [comment]
Reopening. Please note that the mentioned PR https://github.com/o3de/o3de/pull/11084 fixes the error on **opening** a Script Event. This issue is about an error occuring while **saving.** This issue still occurson today's Development (c1c018b) build.
