### ISSUE TITLE
Installer displayed version is not updated to newest release

### ISSUE THREAD

**Issue by LB-HubertUberman** [o3de/o3de#12011]
**Describe the bug**
The latest Stabilization/2210 installer is displaying 0.0.0.0 Development build version instead of 2.2.1.0 Release in various areas. The issue occurs on both Windows and Linux.

Affected areas:

- Installation window.
- Engine directory.
- Splash screen when launching the project.
- Project manager.
- Editor window.

**Steps to reproduce**
1. Download and install the latest Stabilization/2210 installer version of the Engine.
2. Navigate to any of the affected areas.

**Expected behavior**
The installer displays the accurate Engine version.

**Actual behavior**
The installer displayed version is not updated to the newest release.

**Screenshots**
![Installer_InstalationWindow_Version](https://user-images.githubusercontent.com/96232062/190365354-038abb44-eba6-4282-867c-2b4a8ce6c47a.png)
<img width="905" alt="Installer_ProjectManager_Version" src="https://user-images.githubusercontent.com/96232062/190365359-771d8881-de94-4aba-948f-262f478e1f31.png">
<img width="457" alt="Installer_SplashScreen_Version" src="https://user-images.githubusercontent.com/96232062/190365363-232811c6-493c-4e04-9623-ee5b6608475f.png">
<img width="1920" alt="Installer_Editor_Version" src="https://user-images.githubusercontent.com/96232062/190365367-b1571148-c5af-4cea-9129-3327ddb20947.png">
<img width="1006" alt="Installer_Directory_Version" src="https://user-images.githubusercontent.com/96232062/190365883-6990a13b-3fb2-4dbc-a9ad-6ab0cdda596b.png">
<img width="1197" alt="Installer_Linux_InstallWindow_Version" src="https://user-images.githubusercontent.com/96232062/190377113-75615013-cb25-4c04-b6e3-dbe780ccaef0.png">
<img width="1327" alt="Installer_Linux_Directory_Version" src="https://user-images.githubusercontent.com/96232062/190377119-326bb2ce-de63-4f42-9193-a24fc81fcb42.png">

**Found in Branch**
Latest Stabilization/2210 installer

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by amzn-changml** [comment]
Taking a look at the installer pipeline

**Comment by amzn-changml** [comment]
Temporarily resolved by resetting the `O3DE_VERSION` and `O3DE_BUILD_VERSION` environment variables and rebuilding. This PR will more permanently solve the issue: https://github.com/o3de/o3de/pull/12017

**Comment by LB-KacperSzczepanski** [comment]
The same issue occurs in build Stabilization/2210 (840e1f4)

- Splash screen when launching the project.
- Project manager.
- Editor window.

**Comment by amzn-changml** [comment]
@LB-KacperSzczepanski https://github.com/o3de/o3de/pull/12017 has been merged and I've noted that the installer is now displaying the 2210 version number. Can you verify that this is the case?

**Comment by LB-HubertUberman** [comment]
@amzn-changml Verified that Engine is now displaying the 22.10.0 version on latest Stabilization/2210 installer. Also the issue still occurs in build Stabilization/2210 (https://github.com/o3de/o3de/commit/1a540addf51410165f5e05fab275d3ccc9579ace).

**Comment by amzn-changml** [comment]
@LB-HubertUberman There is an environmental variable used on build to define the version (as we don't pin the version directly with the git tag), so building stabilization alone without it will not result in a version number. Here's what you'll need to do for testing it:

In Windows:
```
set O3DE_VERSION=22.10.0
set O3DE_BUILD_VERSION=2210.0

<Run the build>
```

In Ubuntu:
```
export O3DE_VERSION=22.10.0
export O3DE_BUILD_VERSION=2210.0

<Run the build>
```

This can also be defined in the CMake variables as well

**Comment by LB-HubertUberman** [comment]
@amzn-changml I have verified that after setting the environmental variables the version displayed in the affected areas are correct on both Linux and Windows on the latest Stabilization/2210 branch (https://github.com/o3de/o3de/commit/8aa659da364d7fe5f994e192441fbb2b93b0122d).

**Comment by amzn-changml** [comment]
Thanks! I'll go ahead and close this issue as resolved.
