### ISSUE TITLE
Periodic build Bug Report: Linux and Windows awsi_deployment jobs red failing to bootstrap CDK

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#12487]
**Failed Jenkins Job Information:**
Windows
https://jenkins-pipeline.agscollab.com/blue/organizations/jenkins/O3DE-LY-Fork-development_periodic-incremental-daily-internal/detail/O3DE-LY-Fork-development_periodic-incremental-daily-internal/504/pipeline/1319
Linux
https://jenkins-pipeline.agscollab.com/blue/organizations/jenkins/O3DE-LY-Fork-development_periodic-incremental-daily-internal/detail/O3DE-LY-Fork-development_periodic-incremental-daily-internal/504/pipeline/1062

```
aws: error: argument --role-arn: expected one argument

If you don’t want to see a notice anymore, use "cdk acknowledge <id>". For example, "cdk acknowledge 19836".
Unable to resolve AWS account to use. It must be either configured when you define your CDK Stack, or through the environment
[cdk_bootstrap] Failed to bootstrap CDK
```

**Attachments**
[log.txt](https://github.com/o3de/o3de/files/9732758/log.txt)

**Comment by allisaurus** [comment]
Looks like the role ARN which should be set as a build parameter is missing. Need to figure out how to add it back.

**Comment by allisaurus** [comment]
@amzn-changml helped us add the missing params back into the nightly build setup, so this should be fixed next time around assuming they are picked up as expected

**Comment by moraaar** [comment]
The latest nightly build doesn't show the param error, but is still read with the following messages:

On Linux: https://jenkins-pipeline.agscollab.com/blue/organizations/jenkins/O3DE-LY-Fork-development_periodic-incremental-daily-internal/detail/O3DE-LY-Fork-development_periodic-incremental-daily-internal/507/pipeline/477
````
[cdk_deployment] Deploy the CDK application for the AWSCore gem
 /data/workspace/o3de/Gems/AWSCore/cdk /data/workspace/o3de
 /data/workspace/o3de/scripts/build/Platform/Linux/deploy_cdk_applications.sh: line 32: python: command not found
[cdk_deployment] Failed to install required packages for the AWSCore gem
````

On Windows: https://jenkins-pipeline.agscollab.com/blue/organizations/jenkins/O3DE-LY-Fork-development_periodic-incremental-daily-internal/detail/O3DE-LY-Fork-development_periodic-incremental-daily-internal/507/pipeline/530
````
[cdk_deployment] Failed to deploy the CDK application for the AWSCore gem
````

**Comment by allisaurus** [comment]
The [latest](https://jenkins-pipeline.agscollab.com/blue/organizations/jenkins/O3DE-LY-Fork-development_periodic-incremental-daily-internal/detail/O3DE-LY-Fork-development_periodic-incremental-daily-internal/528/pipeline/698/) Windows failure indicates the version of the CDK used to bootstrap the AWS Core stack isn't compatible with the pinned CLI version:
```
[2022-10-31T05:18:11.127Z] This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
[2022-10-31T05:18:11.127Z] (Cloud assembly schema version mismatch: Maximum schema version supported is 18.0.0, but found 20.0.0)
```
...and if you look at preceding logs it looks like the CDK is indeed using a later version of CDKv1 to spin up the stack:
```
[2022-10-31T05:16:31.131Z] Collecting aws-cdk.core>=1.91.0
[2022-10-31T05:16:31.146Z]   Downloading aws_cdk.core-1.179.0-py3-none-any.whl (1.4 MB)
[2022-10-31T05:16:31.146Z]      ---------------------------------------- 1.4/1.4 MB 10.9 MB/s eta 0:00:00
[2022-10-31T05:16:31.405Z] Collecting aws-cdk.aws_iam>=1.91.0
[2022-10-31T05:16:31.419Z]   Downloading aws_cdk.aws_iam-1.179.0-py3-none-any.whl (483 kB)
```

I was able to repro this error locally by setting `CDK_VERSION` to 1.154.0 and trying to run `deploy_cdk_applications.cmd`. 
Setting it to the latest supported CDKv1 version ([1.79.0](https://github.com/aws/aws-cdk/releases/tag/v1.179.0)) seems to resolve it. Will cut a PR to update this for the Periodic builds.

**Comment by moraaar** [comment]
@allisaurus thanks for fixing the AWSI issue on windows.

On Linux it's still failing, could you please take a look? Reopening this issue.

````
/data/workspace/o3de/scripts/build/Platform/Linux/deploy_cdk_applications.sh: line 32: python: command not found
[cdk_deployment] Failed to install required packages for the AWSCore gem
````

https://jenkins-pipeline.agscollab.com/blue/organizations/jenkins/O3DE-LY-Fork-development_periodic-incremental-daily-internal/detail/O3DE-LY-Fork-development_periodic-incremental-daily-internal/530/pipeline/851

**Comment by allisaurus** [comment]
@moraaar apologies for the delay. The awsi_deployment script seems unable to find `python` in its path, which is dynamically built and updated based on params in the build config. We are currently investigating whether the last python upgrade invalidated this path logic.
