### ISSUE TITLE
Linux: Configuring projects fails

### ISSUE THREAD

**Issue by LB-MichalRodzos** [o3de/o3de#15873]
**Describe the bug**
Building projects via the Project Manager fails at Configure step. This issue occurs for the installer (.deb package) build, as well as for Pre-built SDK development build with both default and minimal project templates.

Please refer to the attached logs for more information.

**Steps to reproduce**
1. Install O3DE from .deb package or build the Pre-built SDK.
2. Open the Project Manager.
3. Create a new project.
4. Build the project.

**Expected behavior**
User can build the created project.

**Actual behavior**
Configuring projects fails.

**Attachments:**
[installer_deb.log](https://github.com/o3de/o3de/files/11396893/installer_deb.log)
[pre_built_sdk.log](https://github.com/o3de/o3de/files/11396894/pre_built_sdk.log)

**Found in Branch**
Development
Installer development (.deb package)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
(515f0cc)
https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb

**Desktop/Device:**

- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16 GB

**Comment by lumberyard-employee-dm** [comment]
It looks like the CMake install logic in [Install_common.cmake](https://github.com/o3de/o3de/blob/development/cmake/Platform/Common/Install_common.cmake#L605-L638) isn't taking into account the architecture split for x86_64 and aarch64 on Linux.

If we update the `ly_setup_cmake_install` function to generate the `BuiltinPackages_${PAL_PLATFORM_NAME_LOWER}.cmake` to take the architecture into account, that should resolve the issue.

This can be done by append the `${LY_HOST_ARCHITECTURE_NAME_EXTENSION}` value to the permutation_builtin_file variable that is set as the output name for the generated `BuiltinPackages*.cmake` for Linux.
```cmake
set(permutation_builtin_file ${CMAKE_CURRENT_BINARY_DIR}/cmake/3rdParty/Platform/${PAL_PLATFORM_NAME}/${LY_BUILD_PERMUTATION}/BuiltInPackages_${PAL_PLATFORM_NAME_LOWERCASE}${LY_HOST_ARCHITECTURE_NAME_EXTENSION}.cmake)
```

**Comment by LB-MichalRodzos** [comment]
This issue still occurs on the latest .deb installer. On the GitHub build Development (c5a910b) the issue is fixed. I will verify this issue tomorrow to make sure that we tested installer package with fix included.

**Comment by LB-MichalRodzos** [comment]
Reopening the issue as it still occurs. We verified this issue on two machines using the https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb installer.

**Comment by lumberyard-employee-dm** [comment]
Is the log file for the Debian installer issue still the same?

```
cmake -B build/linux -S . -GNinja Multi-Config -DLY_3RDPARTY_PATH=/root/.o3de/3rdParty
-- Selecting engine '/opt/O3DE/2.1.0' from 'engine_path' in '<project>/user/project.json'.
CMake Error at /opt/O3DE/2.1.0/cmake/3rdParty/BuiltInPackages.cmake:17 (include):
  include could not find requested file:

    /opt/O3DE/2.1.0/cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake
Call Stack (most recent call first):
  /opt/O3DE/2.1.0/cmake/3rdPartyPackages.cmake:712 (include)
  /opt/O3DE/2.1.0/cmake/LYPython.cmake:62 (include)
  /opt/O3DE/2.1.0/CMakeLists.txt:44 (include)


CMake Error at /opt/O3DE/2.1.0/cmake/3rdParty/BuiltInPackages.cmake:29 (add_library):
  add_library cannot create ALIAS target "3rdParty::zlib" because target
  "3rdParty::ZLIB" does not already exist.
Call Stack (most recent call first):
  /opt/O3DE/2.1.0/cmake/3rdPartyPackages.cmake:712 (include)
  /opt/O3DE/2.1.0/cmake/LYPython.cmake:62 (include)
  /opt/O3DE/2.1.0/CMakeLists.txt:44 (include)
```

**Comment by spham-amzn** [comment]
Also I do not see which version of Ubuntu this is being tested on. The debian package is built on Ubuntu 20.04, so it will not work on Ubuntu 22.04. (There is a GHI issue on this right now: https://github.com/o3de/o3de/issues/11640 )

**Comment by spham-amzn** [comment]
> Is the log file for the Debian installer issue still the same?
> 
> ```
> cmake -B build/linux -S . -GNinja Multi-Config -DLY_3RDPARTY_PATH=/root/.o3de/3rdParty
> -- Selecting engine '/opt/O3DE/2.1.0' from 'engine_path' in '<project>/user/project.json'.
> CMake Error at /opt/O3DE/2.1.0/cmake/3rdParty/BuiltInPackages.cmake:17 (include):
>   include could not find requested file:
> 
>     /opt/O3DE/2.1.0/cmake/3rdParty/Platform/Linux/BuiltInPackages_linux_x86_64.cmake
> Call Stack (most recent call first):
>   /opt/O3DE/2.1.0/cmake/3rdPartyPackages.cmake:712 (include)
>   /opt/O3DE/2.1.0/cmake/LYPython.cmake:62 (include)
>   /opt/O3DE/2.1.0/CMakeLists.txt:44 (include)
> 
> 
> CMake Error at /opt/O3DE/2.1.0/cmake/3rdParty/BuiltInPackages.cmake:29 (add_library):
>   add_library cannot create ALIAS target "3rdParty::zlib" because target
>   "3rdParty::ZLIB" does not already exist.
> Call Stack (most recent call first):
>   /opt/O3DE/2.1.0/cmake/3rdPartyPackages.cmake:712 (include)
>   /opt/O3DE/2.1.0/cmake/LYPython.cmake:62 (include)
>   /opt/O3DE/2.1.0/CMakeLists.txt:44 (include)
> ```

I tested the latest debian package on Docker and confirmed that the above was fixed, and I was able to build a default project through the Project Manager.

**Comment by spham-amzn** [comment]
@LB-MichalRodzos Closing this issue for now since I was able to run on a clean ubuntu 20.04 environment. Can you download the latest binary and try again, and re-open and attach logs if there is still an issue
