### ISSUE TITLE
Asset Processor fails to start with a new project and pre-build SDK from Stabilization/2110

### ISSUE THREAD

**Issue by AMZN-Olex** [o3de/o3de#5822]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

Running AssetProcessor on a new project with Pre-build SDK fails with multiple serialization errors, for example:

```
The same component UUID ({D0F440AC-32D4-49EC-8B93-860B188266A6}) / name (ScriptEventReferencesComponent) was registered twice. This isn't allowed, it can cause lifetime management issues / crashes.
This situation can happen by declaring a component in a header and registering it from two different Gems.
```

**Steps to reproduce**
1. Install Pre-build SDK from https://o3debinaries.org/stabilization-2110/Latest/Windows/o3de_installer.exe
2. Create a new project
3. Follow setup instructions by creating a build folder
4. Compile the new project (all good so far)
3. Run AssetProcessor from the installed location, for example: `C:\O3DE\21.10\bin\Windows\profile\Default\AssetProcessor.exe`
4. Observe AssetProcessor

**Expected behavior**
Asset Processor starts up and then completes processing assets.

**Actual behavior**
Asset Processor fails to start with multiple errors such as:

```
The same component UUID ({D0F440AC-32D4-49EC-8B93-860B188266A6}) / name (ScriptEventReferencesComponent) was registered twice. This isn't allowed, it can cause lifetime management issues / crashes.
This situation can happen by declaring a component in a header and registering it from two different Gems.
```

**Assets required**
A brand created project is enough to reproduce this issue.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/5432499/142745330-c7c919e9-ae75-431d-94c2-006bd007aa97.png)

**Found in Branch**
Pre-build SDK from Stabilization/2110

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - CPU Ryzen 5900x
 - GPU NVidia RTX 3090
 - Memory 64GB

**Comment by AMZN-Olex** [comment]
[AP_GUI.908783.log](https://github.com/o3de/o3de/files/7575596/AP_GUI.908783.log)

Here is the AP log. It looks like the error is coming from ScriptEvents gem.

**Comment by Ulrick28** [comment]
This has been resolved

**Comment by carlitosan** [comment]
https://github.com/o3de/o3de/pull/5851

**Comment by carlitosan** [comment]
https://github.com/o3de/o3de/pull/5851

**Comment by LB-MariuszCiechomski** [comment]
The issue still occurs in stabilization branch (99d0c39) and the latest installer. Attaching a video of the outcome.

https://user-images.githubusercontent.com/90192082/143243351-552dec91-a1bb-4491-a6e1-7dca08193d73.mp4

**Comment by LB-TomaszSerwanski** [comment]
We have verified that the issue still occurs in the latest Stabilization_2110 (4d36fb9) when the Game State Samples gem and its dependencies are enabled for the Project.

**Comment by carlitosan** [comment]
The bug has changed, it is no longer a scripting gem that is causing the double registration

![image](https://user-images.githubusercontent.com/82187351/143916651-cd1839b6-6f10-45f4-b43f-06daa8919318.png)

**Comment by amzn-sj** [comment]
Fixed in https://github.com/o3de/o3de/pull/6012

**Comment by LB-TomaszSerwanski** [comment]
The issue verified as Fixed in Stabilization_2110 (6480041).
