### ISSUE TITLE
OnCatalogLoaded is never broadcast if Editor is launched before processing assets

### ISSUE THREAD

**Issue by moraaar** [o3de/o3de#6093]
**Describe the bug**
`OnCatalogLoaded` is a runtime notification for when catalog is loaded and it's possible to resolve asset Ids. Some systems listen to this notification to start loading and resolving their assets, but **this notification is never broadcast if the editor is run without having run Asset Processor first** (which is the default case when creating a project and open editor from Prism tool), leading to some systems (like `PhysXSystem`) not loading and resolving their assets, causing crashes when editor is used (for example #6027)

When the editor is launched first, the asset processor will open and start processing assets, the editor will hold until SOME (not all) assets are processed, then open the editor, but the notification `OnCatalogLoaded` will NEVER be called, even after Asset Processor fully finished.

In the case of launching asset processor first, then wait until all assets are finished, then launch the Editor, the notification `OnCatalogLoaded` will be called correctly.

**Steps to reproduce**
1. Build O3DE with AutomatedTesting project in debug configuration
2. Delete `o3de\AutomatedTesting\Cache` folder if exists.
3. Put a breakpoint in visual studio in `AssetCatalog::LoadBaseCatalogInternal()` function in the line `InitializeCatalog(baseCatalogName.c_str());`
4. Run Editor from visual studio in debug

**Expected behavior**
At some point during editor initialization it should hit the breakpoint to load the catalog and broadcast the `OnCatalogLoaded` notification. 

**Actual behavior**
Breakpoint never hits, meaning `InitializeCatalog` is never called and therefore `OnCatalogLoaded` notification never broadcasted.

**Found in Branch**
Development build (3922280) and Stabilization/2110 (6480041)

**Comment by lumberyard-employee-dm** [comment]
The AssetCatalog gets loaded in the [AzFramework::Application::StartCommon](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Application/Application.cpp#L212-L223) when the `Application::Start` is invoked

**Comment by moraaar** [comment]
Yes, which will call `AssetCatalog::LoadCatalog`, which will call `AssetCatalog::LoadBaseCatalogInternal()` and that function will never reach `InitializeCatalog(baseCatalogName.c_str());` (which is the one broadcasting `OnCatalogLoaded`)

**Comment by AMZN-stankowi** [comment]
Is there a reason these systems are responding to that message? I've found in the cases I've looked at so far, like Atom initializing some systems, it wasn't the right message to listen to. This is for both the reason just pointed out by moraaar, and because in bundled release builds, this message may never be sent because the asset catalog is optional and instead delta catalogs are loaded for each mounted bundle.

**Comment by AMZN-stankowi** [comment]
You can see the change I made to the Atom's bootstrap logic here, to listen for a more reliable message: https://github.com/o3de/o3de/pull/5164/files#diff-1d5588829cc3fe55631fa88df3454631556b59d34e30078021c425963cf75f6bR152

You can see the complete list of application lifecycle events here https://github.com/o3de/o3de/blob/development/Registry/application_lifecycle_events.setreg

**Comment by forhalle** [comment]
@moraaar  - I removed this from Milestone 2. It needs to go through the [exception process](https://wiki.agscollab.com/pages/viewpage.action?spaceKey=lmbr&title=O3DE+Feature+in+Stabilization+Exception+Mechanism) to be considered to be added to scope.

**Comment by yuyihsu** [comment]
@moraaar  what is the user impact to this issue? in the description it only describes the problem, which is failed to call "OnCatalogLoad", but it didn't describe the impact. can you provide more? 
For now we will remove this issue from Milestone 2 until we can assess the impact further.

**Comment by moraaar** [comment]
Fixing this is necessary to fully fix bug #6027, which is marked for RTE Milestone 2. So if #6027 is considered necessary for "RTE Milestone 2" then this issue would need to be included as well. It's explained in detailed in my comment https://github.com/o3de/o3de/issues/6027#issuecomment-984724834

**Comment by moraaar** [comment]
> @moraaar what is the user impact to this issue? in the description it only describes the problem, which is failed to call "OnCatalogLoad", but it didn't describe the impact. can you provide more?
> For now we will remove this issue from Milestone 2 until we can assess the impact further.

I think this part of the description sums it up: "Some systems listen to this notification to start loading and resolving their assets, but this notification is never broadcast if the editor is run without having run Asset Processor first (which is the default case when creating a project and open editor from Prism tool), leading to some systems (like PhysXSystem) not loading and resolving their assets, causing crashes when editor is used (for example #6027)"

Since "OnCatalogLoad" is a basic notification expected by some systems, it's hard to tell the consequence of not calling it, but we can assume those systems won't work as expected, and it's likely they lead to errors or crashes (like the case of #6027).

I did a quick search of `OnCatalogLoad` in the code and these are the systems listening to it:
- FileTag: `ExcludeFileComponent::OnCatalogLoaded`
- Spawnable: `SpawnableSystemComponent::OnCatalogLoaded`
- Material editor viewport: `MaterialViewportComponent::OnCatalogLoaded`
- AtomLyIntegration CommonFeatures: `EditorCommonFeaturesSystemComponent::OnCatalogLoaded`
- AtomLyIntegration PostProcess: `EditorPostFxSystemComponent::OnCatalogLoaded`
- GraphCanvas: ` GraphCanvasSystemComponent`
- Multiplayer NetworkEntity: `NetworkSpawnableLibrary::OnCatalogLoaded`
- PhysXSystem: `PhysXSystem::OnCatalogLoaded` (this is the one caught by #6027)
- SurfaceData: `EditorSurfaceDataSystemComponent::OnCatalogLoaded`

**Comment by moraaar** [comment]
> Is there a reason these systems are responding to that message? I've found in the cases I've looked at so far, like Atom initializing some systems, it wasn't the right message to listen to. This is for both the reason just pointed out by moraaar, and because in bundled release builds, this message may never be sent because the asset catalog is optional and instead delta catalogs are loaded for each mounted bundle.

Yeah, from the `AssetCatalogEvents` bus it seems like `OnCatalogLoaded` is the right one to listen to because it states "it's possible to resolve asset Ids":
````
        /// Game/runtime notification for when catalog is loaded and it's possible to resolve asset Ids.
        virtual void OnCatalogLoaded(const char* /*catalogFile*/) {}
````

I don't know what the other systems listen `OnCatalogLoaded` for, but in the case of PhysXSystem case it was used as a point when the material library asset was expected to be resolved. But if what you're saying it's true, that `OnCatalogLoaded` is optional and cannot be relied on, then we should take a look into all the system where it's used.

**Comment by moraaar** [comment]
> The AssetCatalog gets loaded in the [AzFramework::Application::StartCommon](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Application/Application.cpp#L212-L223) when the `Application::Start` is invoked

@lumberyard-employee-dm  Maybe the initialization of asset catalog should be moved after the editor has stablished a connection with Asset Processor and it has finished processing its asset?

**Comment by AMZN-stankowi** [comment]
I'll look into fixing the missing call to OnCatalogLoaded, but I think each of those systems should be evaluated and probably switched to a different message. I also don't think it will fix the crash in this ticket, because if you're loading a project with a lot of assets to process there's nothing stopping you from clicking through to the tool and causing the crash while assets are still processing. That crash should be addressed in that system.

**Comment by moraaar** [comment]
> I also don't think it will fix the crash in this ticket, because if you're loading a project with a lot of assets to process there's nothing stopping you from clicking through to the tool and causing the crash while assets are still processing. That crash should be addressed in that system.

PR #6050 fixed the crash for PhysXSystem, but physx materials shown in FBX Settings are still not behaving as it should (it only shows default material, instead of all the materials from the library). But that will get fixed once this `OnCatalogLoaded` issue is addressed.

**Comment by yuyihsu** [comment]
> > @moraaar what is the user impact to this issue? in the description it only describes the problem, which is failed to call "OnCatalogLoad", but it didn't describe the impact. can you provide more?
> > For now we will remove this issue from Milestone 2 until we can assess the impact further.
> 
> I think this part of the description sums it up: "Some systems listen to this notification to start loading and resolving their assets, but this notification is never broadcast if the editor is run without having run Asset Processor first (which is the default case when creating a project and open editor from Prism tool), leading to some systems (like PhysXSystem) not loading and resolving their assets, causing crashes when editor is used (for example #6027)"
> 
> Since "OnCatalogLoad" is a basic notification expected by some systems, it's hard to tell the consequence of not calling it, but we can assume those systems won't work as expected, and it's likely they lead to errors or crashes (like the case of #6027).

Thanks @moraaar  for the detailed info. I agree with you that this issue is bigger than my original understanding. I agree that we should fix this in the RTE point release. @forhalle let me know if you have concern to add this back to the milestone 2 scope. It seems that the team has a solution already as well.

**Comment by lumberyard-employee-dm** [comment]
> > I also don't think it will fix the crash in this ticket, because if you're loading a project with a lot of assets to process there's nothing stopping you from clicking through to the tool and causing the crash while assets are still processing. That crash should be addressed in that system.
> 
> PR #6050 fixed the crash for PhysXSystem, but physx materials shown in FBX Settings are still not behaving as it should (it only shows default material, instead of all the materials from the library). But that will get fixed once this `OnCatalogLoaded` issue is addressed.

I agree with Joseph in this case that the `OnCatalogLoaded` event is not the correct the event to use determine whether a specific asset has processed.
`OnCatalogLoaded` doesn't mean the "AssetProcessor has processed ALL the assets and the application can now load those assets".
It just means that the application has performed call to `AssetCatalogBus::LoadCatalog` for a particular xml file that contains a list of known AssetIds.

Furthermore the AssetProcessor isn't obliged to process a PhysX material asset before the Editor initializes the PhysXSystem unless the PhysXSystem itself forces a compile of that asset via the [AssetSystemBus](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Asset/AssetSystemBus.h#L191-L203)

**Comment by moraaar** [comment]
>Furthermore the AssetProcessor isn't obliged to process a PhysX material asset before the Editor initializes the PhysXSystem unless the PhysXSystem itself forces a compile of that asset via the AssetSystemBus

About this particular point, the `.physmaterial` assets have been marked as critical assets in PR #6050 
Editor is not suppose to open until all critical assets have been processed (or so I thought, please let me know if that's not the case)

**Comment by moraaar** [comment]
> I agree with Joseph in this case that the OnCatalogLoaded event is not the correct the event to use determine whether a specific asset has processed.
OnCatalogLoaded doesn't mean the "AssetProcessor has processed ALL the assets and the application can now load those assets".
It just means that the application has performed call to AssetCatalogBus::LoadCatalog for a particular xml file that contains a list of known AssetIds.

Thanks for the clarification, if that's the case, then yeah, all those systems using `OnCatalogLoaded` need to be revisited and validated if they are using it for the right purpose.

**Comment by lumberyard-employee-dm** [comment]
> > Furthermore the AssetProcessor isn't obliged to process a PhysX material asset before the Editor initializes the PhysXSystem unless the PhysXSystem itself forces a compile of that asset via the AssetSystemBus
> 
> About this particular point, the `.physmaterial` assets have been marked as critical assets in PR #6050 Editor is not suppose to open until all critical assets have been processed (or so I thought, please let me know if that's not the case)

The Editor doesn't open until after it processes all critical assets, but that Editor doesn't have to load the `AssetCatalog` if it doesn't exists.
The AssetProcessor is launched in [CryEdit::InitInstance](https://github.com/o3de/o3de/blob/development/Code/Editor/CryEdit.cpp#L1663-L1665) after the AzFramework::Application has attempted to load an already processed assetcatalog.xml that was in the Cache on startup. This call is triggered via the `AZToolsApp.Start()` call  in [CryEditMain](https://github.com/o3de/o3de/blob/development/Code/Editor/CryEdit.cpp#L4174-L4183).

I think if you want to make sure that a specific `.physmaterial` is available, you would also have to handle the [AssetCatalogBus::OnAssetCatalogAdded](https://github.com/o3de/o3de/blob/development/Code/Framework/AzFramework/AzFramework/Asset/AssetCatalogBus.h#L38-L39) notification as well

**Comment by moraaar** [comment]
>I think if you want to make sure that a specific .physmaterial is available, you would also have to handle the AssetCatalogBus::OnAssetCatalogAdded notification as well

The issue is that we still need a point in time to know when to give up waiting for a `OnCatalogAssetAdded` that might never come and do something else instead.

**Comment by lawsonamzn** [comment]
OnAssetCatalogLoaded doesn't indicate that any particular asset is ready, only that the game has loaded the AssetCatalog.xml file and can start responding to requests about assets.  

It is not meant to be guaranteeing anything except that those APIs are now available, not that your assets are ready.

**If you have a system that has required assets that cannot hotload reload (Why??)**
* Call EscalateAssetByUuid or EscalateAssetBySearchTerm as early as possible to make sure the asset(s) you're about to load are at the top of the compile queue.
* When you wanna load your asset, try to load it, and if it fails, call CompileAssetSyncById (or by name) and try again (or call CompileAssetSyncById before each load if theres just a few of them.  This call costs maybe a milisecond so don't spam.).  This call will ensure the asset is both ready for you and in the catalog and will also escalate it to the top of the queue and process it asap.  It will block until the asset is ready.

**If you have a system thats capable of hot loading assets or reloading them (the standard!)**
* implement the fallback default handler virtual function which can substitute a standby/default asset in the place of your asset.
* In that default handler, CompileAssetSyncById the default asset to ensure the default fallback is available.
* In that default handler, EscalateAssetByUuuid the asset asked for so that it will priority compile the missing asset
* In your thing which holds a reference to the asset (ie, an ASset<t>) implement and listen for the OnAssetReloaded message and update your pointers when it reloads.  You will receive this automatically.

**Comment by moraaar** [comment]
In the case of PhysX System and its material library asset, it does support material library hot reloading, but reloading a material library has side effects, all components in a level using physics materials will be notified and those using a material that is not available in the library will be set to default, so we do want to settle the material library before the user has the change to load levels or use the editor.

It's ok for the user to change the material library later in the editor, as it's up to them to face the consequences of switching libraries, but if it's the system that changes the material library "on the fly" because of async asset loading, then it will be seem as an error when all level's components suddenly use the default materials instead of what they had before.

My code can easily ask to load an asset and handle if that asset doesn't exists to do something else instead (use default material library), but what it seems unnecessary complicated is that my code has to handle **when it can ask the question** if an asset exists and do this extra communication with Asset Processor to scale an asset priority... It seems like a system notification is needed to at least notify that critical assets are ready in the catalog.

**Comment by moraaar** [comment]
For PhysX System it works fine by listening to `LegacySystemInterfaceCreated` (like Atom boostrap suggested by @AMZN-stankowi), because it's called after critical assets have been processed and physics materials have been marked as criticals (https://github.com/o3de/o3de/pull/6168)

This solution is good enough for PhysX System without having to make large changes. The other usages of `OnCatalogLoaded` would have to be analyzed and see if they need to be modified.

**Comment by lawsonamzn** [comment]
Note that its still a bug that this event OnCatalogLoaded does not fire in this situation.  Its not the right event to listen to, for sure, since it doesn't indicate what assets are ready and what are not (Besides criticals), but if its not firing, something has gone wrong.   

The Editor used to first connect to the AP, then wait for all criticals to be done and then send a signal to the AP to force it to flush the asset catalog xml file.  The request to flush it would block until it was done writing the file and flushing it.  Only then would it load it, and then signal OnCatalogLoaded.  

Is it possible that all the shuffling and startup / legacy removal has caused this sequence to change?

**Comment by forhalle** [comment]
@yuyihsu  - Is this an RTE issue? What workflow? There are no workflow labels.

**Comment by yuyihsu** [comment]
this is the long-term fix related to this ticket: https://github.com/o3de/o3de/pull/6347. We will keep it in the future scope.
