### ISSUE TITLE
Using Center on Selection action on very distant entities can cause the Viewport Camera to flip its orientation

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6243]
**Describe the bug**
If an entity, that is very far away from the camera, is selected, and then the Center on Selection action is performed on it, the Viewport Camera can flip its orientation, making it difficult to rotate properly.

**Steps to reproduce**
1. Create a new level.
2. Create a new entity.
3. Set the created entity's Translate to X: 50, Y: 50, Z: 99999.
4. Make sure the created entity is selected.
5. Go to View > Center on Selection (Or press Z).

**Expected behavior**
The Viewport Camera centers on the selected entity without issues.

**Actual behavior**
The Viewport Camera centers on the selected entity, but flips its orientation.

**Video**

https://user-images.githubusercontent.com/86952082/145184955-05a8d774-2577-43f2-9a4e-5d21df6d28a4.mp4

**Found in Branch**
Development (a8ef23e)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600 6-Core Processor, 3600 MHz, 6 Core(s), 12 Logical Processor(s)
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by hultonha** [comment]
Hmm this does not so much appear to be objects that are far away but objects that are directly above or below the camera (looking directly up or down is generally something we try and avoid). This is something I can look into clamping to prevent this from occurring.

It will most likely be down to a singularity the camera can get into when looking straight up or down.

**Comment by hultonha** [comment]
This should be fixed by https://github.com/o3de/o3de/pull/15362, once it's merged if you could please retest I'd really appreciate it @LB-ArturZieba 👍

**Comment by LB-ArturZieba** [comment]
@hultonha Okay, I will verify this once the PR is merged.

**Comment by hultonha** [comment]
Thanks @LB-ArturZieba, I just need to fix one test (likely later today). I'll let you know when it's merged. Thanks!

**Comment by hultonha** [comment]
Now merged https://github.com/o3de/o3de/pull/15362, closing.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Stabilization/2305 (392d44b) build, however it still occurs on Development (7244dec).

**Comment by hultonha** [comment]
FYI this will happen in development until the next `stabilization/2305`->`development` merge happens (which will likely be next week)
