### ISSUE TITLE
Reloading the Platform Settings with the Android Icons list expanded crashes the Editor

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#7314]
**Describe the bug**
If the _Platform Settings_ are reloaded with the _Android Icons_ list expanded, the Editor crashes.

Please note that the error.log is not generated after the issue.

Please refer to the attached video and editor.log for more details.

**Steps to reproduce**
1. Go to _File_ -> _Edit Platform Settings..._.
2. Expand the _Icons_ under _Android_ _Platform Settings_.
3. Press _Reload_ and confirm by pressing _Reset_.

**Expected behavior**
Platform Settings are reloaded. The Editor remains stable.

**Actual behavior**
The Editor crashes.

**Assets required**
N/A

**Screenshots/Video**

https://user-images.githubusercontent.com/86953108/151945151-ac80cf88-abb7-4c0f-adf0-344a732cb892.mp4

**Found in Branch**
Development (f5fcab7)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 SUPER
 - Memory 16GB

**Attachments**
[Editor.log](https://github.com/o3de/o3de/files/7977349/Editor.log)

**Comment by jjjoness** [comment]
Thanks Danilo,

I’m setting up a clean branch to test this as I can’t reproduce it in my current branch.

Any info will be much appreciated.

Cheers,

John

**Comment by AMZN-daimini** [comment]
I can't seem to repro either, but watching the video once more I noticed that my project has default icons showing when I open that pane, while they don't:
![image](https://user-images.githubusercontent.com/82231674/152082040-4bd69d32-9e72-48c2-86ef-dff875a80f1f.png)

So I think we may have to create a new project and repro with that.

**Comment by jjjoness** [comment]
@AMZN-daimini I have made two empty projects and they both contain the icons!

**Comment by jjjoness** [comment]
@LB-TomaszSerwanski Can you let me have a way to reproduce this? I have tried making new projects and it still doesn't occur.

**Comment by jjjoness** [comment]
@AMZN-daimini The missing icons was tracked down to the installer not installing the Android files. I have contacted Prism and this will be fixed in the next installer. Still tracing the crash.

**Comment by jjjoness** [comment]
@AMZN-daimini This only happens because the installer for the released version doesn't install the icons. It has been reported and should be fixed by the installer team. Can this be closed?

**Comment by AMZN-daimini** [comment]
If there's an issue for the reported issue on the installer, we should link these and verify this no longer repros when that change goes in.

**Comment by moraaar** [comment]
This issue seems pretty old. I tested this today with the latest code, the editor didn't crash when clicking on Reload and the o3de icons were present. 

@LB-TomaszSerwanski can you verify and close the bug if it doesn't reproduce anymore please? Thanks.

**Comment by LB-TomaszSerwanski** [comment]
@moraaar I have verified that the issue still occurs on both Source as well as the Pre-built SDK engine, however it now requires an extra step. The modified reproduction steps are as follows:

1. Build the Pre-built SDK Engine using the [official guide](https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/building-windows/).
2. Create a new Project (either a Standard Template or with all gems enabled).
3. Build the Project.
4. Launch the Editor.
5. Create a new level.
6. Go to File -> Edit Platform Settings.
7. Expand the Icons list.
8. Modify any setting - i.e. enable the _Use Main APK_ option (this one is new, as without it pressing the _Reload_ button does not have any effect).
9. Press Reload.
10. Select Reset.

As for the o3de icons - they are only missing on the Pre-built SDK engine, and are present on the Source build. This has been verified on the latest Stabilization/2210 (0fd1b90) as well as the Development (3b58972) branches.

**Comment by moraaar** [comment]
Thanks for confirming @LB-TomaszSerwanski.

I will remove the platform/android label, since the issue occurs on PC, not on android.

sig/content seems to be the better fit to look at this issue, since it's editor related.

For the icons missing on pre-build sdk that seems to be covered by this other GHI https://github.com/o3de/o3de/issues/3881 so it'd be better to not mix them both and focus this one on the editor crash only.
